# ┌────────────────────────────────
# │ Настройки одного из самых интересных методов аутентификации - бот Discord.
# │
# │ Его интерфейс знаком многим игрокам, а функции достаточно широки: 2FA, настройки, уведомления и так далее.
# │
# │ [!] Для настройки вам стоит следовать гайду, это займёт всего пару минут:
# │ https://blackbaroness.github.io/docs/pages/baronessauth/guide/discord.html
# │
# │ Поддерживается форматирование, чтобы, например, делать текст **жирным**:
# │ https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline
# │
# │ Этот метод хорошо переносит /auth reload - вы можете даже сменить токен, не перезагружая прокси.
# └────────────────────────────────
enabled: false

# Человеческое название этого способа, чтобы в редких случаях показать игрокам.
display-name: '2FA в Discord'

# ┌────────────────────────────────
# │ Настройки бота - данные для подключения, сообщения, клавиатура и так далее
# └────────────────────────────────
bot:
  # Токен для доступа к боту.
  token: 'вставьте токен сюда'

  # Команды для ввода кода. Если указать пустую команду, любое сообщение будет считаться попыткой ввести код.
  commands:
  - ''
  - '/привязать'
  - '!привязать'
  - '/привязка'
  - '!привязка'
  - '/link'

  # Принимать корректные коды, даже если команда была указана неправильно? На случай тупняка игроков.
  handle-valid-code-even-when-command-is-invalid: true

  # Обрабатывать ли нажатия кнопок, которые были созданы не этим ботом? (ботом до 3.0.0 или вообще чужим)
  handle-unknown-button-click: true

  # Здесь можно включить требование быть членом сервера, прежде чем пользоваться ботом.
  # [ВАЖНО] Вы должны добавить бота на эти сервера.
  require-server-membership:
    enabled: false
    server-ids:
    - 1271734438774177864
    message: '⛔ Для использования бота вы должны быть членом сервера <вставьте своё>.'

  # По умолчанию бот принимает коды привязки только в ЛС, но вы можете выделить для этого и канал на сервере.
  # [ВАЖНО] Вы должны добавить бота на сервера, к которым относятся эти каналы.
  # [ВАЖНО] У бота должен быть полный доступ к этим каналам.
  link-using-channel:
    enabled: false
    channel-ids:
    - 1271734438774177867

  # Менять ли отображаемое имя игрока после успешной привязки?
  # [ВАЖНО] Вы должны добавить бота на сервера, которые вы указываете здесь.
  # [ВАЖНО] У бота на сервере должны быть права на это.
  set-name-after-link:
    enabled: false
    server-ids:
    - 1271734438774177864

  # Выдавать ли пользователю роль после успешной привязки?
  # [ВАЖНО] Вы должны добавить бота на сервера, которые вы указываете здесь.
  # [ВАЖНО] У бота на сервере должны быть права на это.
  set-role-after-link:
    enabled: false
    # ID сервера │ ID роли
    server-id-to-role-id:
      1271734438774177864: 1407079838207971409

  # Забирать ли у пользователя роль после успешной привязки?
  # [ВАЖНО] Вы должны добавить бота на сервера, которые вы указываете здесь.
  # [ВАЖНО] У бота на сервере должны быть права на это.
  remove-role-after-link:
    enabled: false
    # ID сервера │ ID роли
    server-id-to-role-id:
      1271734438774177864: 1407079838207971409

  # Максимально допустимое время ожидания ответа от Discord.
  # Можно аккуратно повышать, если бот ловит ошибку timeout.
  # Можно поменять без рестарта - /auth reload подхватит.
  timeout:
    # Максимальное время для установки контакта с удалённым сервером.
    connect: '3 сек'
    # Максимальное время между двумя пакетами данных при обмене данными с сервером.
    socket: '5 сек'
    # Максимальная длительность всего HTTP запроса - от отправки до получения ответа.
    request: '10 сек'

  # Прокси для подключения к Discord.
  # Обязательно к прочтению: https://blackbaroness.github.io/docs/pages/baronessauth/guide/proxy.html
  proxy:
    enabled: false
    protocol: !<http>
      url: 'http://example.com:8080'
    extra-headers: {}

  # ┌────────────────────────────────
  # │ Тут находятся все сообщения бота.
  # └────────────────────────────────
  messages:

    # Когда пользователь вызвал невозможное действие (например, пытается привязать аккаунт, который уже удалён).
    invalid-action: '❓ Это действие больше неактуально.'

    # Когда пользователь исчерпал лимит привязки игроков к аккаунту.
    too-many-links-for-account: '⭕ Вы не можете привязать ещё больше игроков к этому
      аккаунту.'

    # Когда нужно сделать что-то с игроком, а он оффлайн.
    player-is-offline: '⭕ Игрок <name> не в сети.'

    # Когда включено подтверждение привязки.
    link-confirmation-required: '⚠ Почти готово! Теперь вернитесь в игру и прочтите
      сообщение в чате.'

    # Когда пользователь успешно привязал аккаунт.
    successful-link: '✅ Вы успешно привязали аккаунт <name>!'

    # Когда пользователю нужно выбрать аккаунт (если у него их несколько).
    select-account: 'Выберите аккаунт:'

    # Когда пользователю нужно принять или отклонить запрос 2FA.
    2fa-request-start: |-
      ⚠ На ваш аккаунт, <name>, пытаются войти с IP <address> (<city>, <country>).

      Тот, кто пытается войти, правильно ввёл ваш пароль!
      Если это не вы, отклоните и смените пароль немедленно (нажмите "сброс пароля")!

    # Когда пользователь принял запрос 2FA.
    2fa-request-accept: '✅ Вы приняли вход на аккаунт <name> с IP <address> (<city>,
      <country>).'

    # Когда пользователь отклонил запрос 2FA.
    2fa-request-decline: |-
      ⭕ Вы отклонили вход на аккаунт <name> с IP <address> (<city>, <country>).

      Если это были не вы, смените пароль немедленно (нажмите "сброс пароля")!

    # Когда пользователь отклонил запрос 2FA.
    2fa-request-cancel: |-
      ⭕ На ваш аккаунт, <name>, пытались войти с IP <address> (<city>, <country>).

      Процесс был отменён - игрок не вошёл.

      Если это были не вы, смените пароль немедленно (нажмите "сброс пароля")!

    # Уведомление при успешном логине.
    notification-login: |-
      🔔 На ваш аккаунт, <name>, вошли, используя <methods>.
      Вход был с IP <address> (<city>, <country>).

    # Когда пользователь слишком часто обращается к боту.
    action-rate-limit: '❄ Подождите, прежде чем совершать очередное действие.'

    # Когда пользователь обращается к боту, не дождавшись прошлого ответа.
    previous-action-still-active: '⏳ Ваш прошлый запрос ещё активен, дождитесь его
      конца!'

    # Когда пользователь не указал код в сообщении.
    invalid-input: |-
      ❓ Вы хотели привязать аккаунт?
      Зайдите на сервер, введите `/link discord` и полученный код отправьте сюда.

    # Когда пользователь указан неактивный код.
    unknown-code: |-
      ❓ Неизвестный код.
      Зайдите на сервер и введите `/link discord`, чтобы получить новый.

  # ┌────────────────────────────────
  # │ находятся все кнопки бота.
  # └────────────────────────────────
  buttons:

    # Здесь можно расположить кнопки:
    #    STATUS
    #    RESET_PASSWORD
    #    SETTINGS
    #    TOGGLE_BLOCK
    #    UNLINK
    #    KICK
    #    HELP
    main-keyboard-layout:
    - - 'STATUS'
    - - 'RESET_PASSWORD'
      - 'SETTINGS'
    - - 'TOGGLE_BLOCK'
      - 'UNLINK'
      - 'KICK'
    - - 'HELP'

    # Здесь можно расположить кнопки:
    #   ENABLE_2FA
    #   DISABLE_2FA
    #   ENABLE_NOTIFICATIONS
    #   DISABLE_NOTIFICATIONS
    #   ENABLE_SESSIONS
    #   DISABLE_SESSIONS
    #   CLOSE_SETTINGS
    settings-keyboard-layout:
    - - 'ENABLE_2FA'
      - 'DISABLE_2FA'
    - - 'ENABLE_NOTIFICATIONS'
      - 'DISABLE_NOTIFICATIONS'
    - - 'ENABLE_SESSIONS'
      - 'DISABLE_SESSIONS'
    - - 'CLOSE_SETTINGS'

    2fa-request:
      accept: '✅ Разрешить'
      decline: '❌ Отклонить'

    status:
      label: '📑 Статус'
      output: |-
        👤 Аккаунт: <name> — <online>

        📅 Последний вход: <last_login_date>
        🌍 Последний IP: <last_ip> (<last_ip_city>, <last_ip_country>)

        <notifications>

        <2fa>

        <sessions>

        <block>
      online:
        yes: 'Онлайн 🟢'
        no: 'Оффлайн 🔴'
      notifications:
        yes: |-
          🔔 Уведомления: ✅ Включены
          Вы получите сообщение при успешном входе
        no: |-
          🔔 Уведомления: ❌ Выключены
          Бот не сообщает о входах
      2fa:
        yes: |-
          🔐 2FA: ✅ Включена
          Для входа нужно подтверждение
        no: |-
          🔐 2FA: ❌ Выключена
          Подтверждение для входа не требуется
      sessions:
        yes: |-
          💻 Cессии: ✅ Включены
          Мгновенный вход с того же IP
        no: |-
          💻 Cессии: ❌ Выключены
          Всегда нужна аутентификация
      block:
        yes: '🚫 Ручная блокировка: установлена'
        no: '🚫 Ручная блокировка: нет'

    reset-password:
      label: '🔐 Сброс пароля'
      in-progress: '🔐 Генерируем пароль для <name>... ⏳'
      success: '🔐 Новый пароль для <name>: <password>'

    settings:
      label: '⚙ Настройки'
      open: '⚙ Вы открыли меню настроек.'
      close: '⚙ Вы закрыли меню настроек.'

    toggle-block:
      label: '⛔ Блокировка'
      success: |-
        ️️️⛔️ Вы переключили блокировку <name>, теперь она <status>.

        Заблокированный аккаунт не сможет входить на сервер, пока вы его не разблокируете.
      enabled: 'включена (вход запрещён)'
      disabled: 'выключена (вход разрешён)'

    unlink:
      label: '⭕ Отвязка'
      confirmation-description: '⚠ Это действие необратимо!'
      confirmation-yes: '⭕ Я хочу отвязать <name>.'
      confirmation-no: '🟢 Нет, не хочу.'
      success: '⭕ Вы отвязали <name> от этого аккаунта.'
      cancel: 'Вы решили не отвязывать <name> от этого аккаунта.'

    kick:
      label: '💢 Кикнуть'
      success: '💢 Вы кикнули <name>.'
      target-offline: '❌ На сервере сейчас нет <name>.'
      kick-reason: '<red>Владелец аккаунта кикнул вас из бота привязки.'

    help:
      label: '📞 Помощь'
      message: 'Нажмите, чтобы обратиться за помощью:'
      url-button: '📞 Обратиться за помощью'
      url: 'https://blackbaroness.github.io/docs/pages/baronessauth/default_help_link'

    enable-2fa:
      label: '✅ ВКЛ 2FA'
      success: |-
        ✔ Вы включили 2FA для <name>.

        Теперь, при попытке входа на ваш аккаунт, этот бот будет требовать подтверждение.
    disable-2fa:
      label: '❌ ВЫКЛ 2FA'
      success: |-
        ⭕ Вы выключили 2FA для <name>.

        Теперь этот бот не будет требовать никаких подтверждений при попытке входа на ваш аккаунт.

    enable-notifications:
      label: '✅ ВКЛ уведомления'
      success: |-
        ✔ Вы включили уведомления для <name>.

        Теперь бот будет уведомлять вас, когда на ваш аккаунт успешно вошли.
    disable-notifications:
      label: '❌ ВЫКЛ уведомления'
      success: |-
        ⭕ Вы выключили уведомления для <name>.

        Теперь бот не будет уведомлять вас, когда на ваш аккаунт успешно вошли.

    enable-sessions:
      label: '✅ ВКЛ сессии'
      success: |-
        ✔ Вы включили сессии для <name>.

        Теперь вы можете мгновенно входить на сервер, если недавно уже входили с того же IP адреса.
    disable-sessions:
      label: '❌ ВЫКЛ сессии'
      success: |-
        ⭕ Вы выключили сессии для <name>.

        Теперь ваш вход всегда будет требовать аутентификации, даже если вы входите с того же IP адреса.

    close-settings:
      label: '🚪 Закрыть'

# ┌────────────────────────────────
# │ Настройки привязки со стороны игрока (/link discord).
# └────────────────────────────────
link:
  # Поставьте false, если хотите оставить метод включённым, но запретить новые привязки.
  accept-new: true

  # Сколько игровых ников можно привязать к одному аккаунту? (абсолютный максимум = 25)
  max-links-per-account: 25

  # Это сообщение видит игрок при начале привязки.
  in-game-start-message: |-
    <gradient:#ffdd00:#fff457><bold>││││ Привязка к Discord</bold></gradient>
    <color:#ffdd00><bold>│</bold></color> <gray>1.</gray> Вот вам код <click:copy_to_clipboard:'<code>'><hover:show_text:'Нажмите, чтобы скопировать!'><u><code></u></hover></click>
    <color:#ffdd00><bold>│</bold></color> <gray>2.</gray> Перейдите к боту <click:open_url:'https://discord.com/channels/@me/1406953977962172477'><u>BaronessAuth-test</u></click>
    <color:#ffdd00><bold>│</bold></color> <gray>3.</gray> Отправьте ему этот код

  # Это сообщение видит игрок после успешной привязки.
  in-game-success-message: '<green>Вы успешно привязали себя к Discord <name>!'

  # Когда пользователь исчерпал лимит привязки игроков к аккаунту.
  in-game-too-many-links-for-account: '<red>Вы не можете привязать ещё больше аккаунтов
    к этому Discord.'

  # Подтверждение при привязке, чтобы избежать угона аккаунтов через демонстрацию первоначального кода.
  confirmation:
    enabled: true
    in-game-message: |-
      <bold><color:#ff0000>[!]</color> <color:#fa414a>↓↓↓ Прочитайте — вас могут скамить! ↓↓↓</color></bold>
      <bold><color:#ff0000>[!]</color> </bold>
      <bold><color:#ff0000>[!]</color> </bold><yellow>Если вы 100% уверены, что хотите привязать свой аккаунт в <u>Discord <name></u>, введите /link <code>.
      <bold><color:#ff0000>[!]</color> </bold>
      <bold><color:#ff0000>[!]</color> </bold><yellow>Если вы не хотите, просто проигнорируйте это сообщение.
      <bold><color:#ff0000>[!]</color> </bold>
      <bold><color:#ff0000>[!]</color> <color:#fa414a>↑↑↑ Прочитайте — вас могут скамить! ↑↑↑</color></bold>

  # Список команд, которые выполняются консолью при успешной привязке. <player> заменяется на имя игрока.
  execute-console-commands-after-successful-link: []

# ┌────────────────────────────────
# │ Некоторые сообщения, отображаемые в игре.
# └────────────────────────────────
in-game-messages:
  2fa-declined: '<red>Вход был отклонён в Discord боте.'
  connect-rejected-because-of-block: '<red>Аккаунт был заблокирован через привязанный
    Discord бот.'
  chat-blocked: '<red>Discord бот не может отправить вам сообщение. Вы его заблокировали?'

# ┌────────────────────────────────
# │ Настройки логина.
# └────────────────────────────────
login:

  # ┌────────────────────────────────
  # │ Настройки того, что происходит ДО успешного логина.
  # └────────────────────────────────
  before:

    # ┌────────────────────────────────
    # │ Максимальное время, которое игрок может провести в этом состоянии.
    # │ Если игрок не успеет залогиниться, он будет кикнут.
    # └────────────────────────────────
    timeout:
      maximum-time: '2 мин'
      kick-message: '<red>Вы не успели подтвердить вход в боте Discord вовремя.'
      # Отображает боссбар, пока игрок не залогинился.
      # Полоска боссбара постепенно уменьшается в соответствии с таймаутом (см. timeout).
      # Плейсхолдер <remaining_time> меняется на оставшиеся секунды.
      bossbar:
        enabled: true
        content: '<gradient:#FF5722:#FF9800><bold>[!]</bold></gradient> <white>Подтвердите
          вход </white><gold>в боте Discord</gold> <gray>(<remaining_time>s)'
        color: 'YELLOW'
        overlay: 'PROGRESS'
    # Отправляет сообщения по очереди, с равным интервалом, пока игрок не залогинился.
    message:
      enabled: false
      rate: '4 сек'
      contents:
      - '<gradient:#F9A825:#FFEB3B><bold>[!]</bold></gradient> <white>Подтвердите
        вход</white> <gold>в боте Discord</gold>'
    # Отправляет тайтлы (сообщения на весь экран), пока игрок не залогинился.
    title:
    - title: '<gradient:#FFA000:#FFC107><bold>Подтвердите вход</bold></gradient>'
      subtitle: '<white>в боте <gold>Discord</gold>'
      duration-fade-in: '500 мсек'
      duration-stay: '1 ч'
      duration-fade-out: '500 мсек'

  # ┌────────────────────────────────
  # │ Настройки того, что происходит ПОСЛЕ логина.
  # │ Сервер, куда игрока отправит, настраивается в general.yml.
  # └────────────────────────────────
  after-full:

    # Определяет, сколько времени плагин подержит игрока, прежде чем телепортировать его.
    delay: '2 сек'

    # Отправляет сообщение на весь экран об успешном логине.
    title:
      enabled: true
      title: '<green>С возвращением!'
      subtitle: '<green>Вы успешно вошли!'
      duration-fade-in: '500 мсек'
      duration-stay: '3 сек 500 мсек'
      duration-fade-out: '1 сек'

    # Отправляет сообщение в чат об успешном логине.
    message:
      enabled: false
      content: '<green>Вы успешно вошли!'

  # ┌────────────────────────────────
  # │ Настройки того, что происходит ПОСЛЕ логина, но когда остались ещё 2FA.
  # └────────────────────────────────
  after-partial:

    # Определяет, сколько времени плагин подержит игрока, прежде чем перейти к следующей проверке.
    delay: '1 сек 400 мсек'

    # Сообщение на весь экран.
    title:
      enabled: true
      title: '<green>Вход подтверждён!'
      subtitle: '<gray>Проверки сейчас продолжатся...'
      duration-fade-in: '300 мсек'
      duration-stay: '800 мсек'
      duration-fade-out: '300 мсек'

    # Сообщение в чате.
    message:
      enabled: false
      content: '<green>Вход подтверждён! <gray>Продолжаем...'

