# ┌────────────────────────────────
# │ Настройки самого типичного способа аутентификации — по паролю.
# │ Здесь всё, что касается /register и /login.
# │ 
# │ Этот способ — единственный, что позволяет зарегистрироваться.
# │ Отключив его, вы запретите незарегистрированным игрокам заходить на сервер.
# └────────────────────────────────

enabled: true

# Человеческое название этого способа, чтобы в редких случаях показать игрокам.
display-name: 'пароль'

# ┌────────────────────────────────
# │ Настройки регистрации.
# └────────────────────────────────
registration:
  # ┌────────────────────────────────
  # │ Команда /register [пароль] [отключаемо: повтор пароля].
  # └────────────────────────────────
  command:
    aliases:
    - 'register'
    - 'reg'
    cooldown: '700 мсек'
    arguments:
      password: 'пароль'
      password-repeat: 'повтор пароля'
      password-repeat-required: true

  # ┌────────────────────────────────
  # │ Настройки того, что происходит ДО успешной регистрации.
  # └────────────────────────────────
  before:
    # ┌────────────────────────────────
    # │ Максимальное время, которое игрок может провести в этом состоянии.
    # │ Если игрок не успеет зарегистрироваться, он будет кикнут.
    # └────────────────────────────────
    timeout:
      maximum-time: '2 мин'
      kick-message: '<red>Вы не успели зарегистрироваться вовремя.'
      # ┌────────────────────────────────
      # │ Отображает боссбар, пока игрок не зарегистрировался.
      # │ Полоска боссбара постепенно уменьшается в соответствии с таймаутом (см. timeout).
      # │ Плейсхолдер <remaining_time> меняется на оставшиеся секунды.
      # └────────────────────────────────
      bossbar:
        enabled: true
        content: '<gradient:#FF5722:#FF9800><bold>[!]</bold></gradient> <white>Зарегистрируйтесь:
          </white><gold>/reg пароль повтор</gold> <gray>(<remaining_time>s)'
        color: 'YELLOW'
        overlay: 'PROGRESS'
    # ┌────────────────────────────────
    # │ Отправляет сообщения по очереди, с равным интервалом, пока игрок не зарегистрировался.
    # └────────────────────────────────
    message:
      enabled: false
      rate: '4 сек'
      contents:
      - '<gradient:#F9A825:#FFEB3B><bold>[!]</bold></gradient> <white>Придумайте пароль
        и введите</white> <gold>/reg пароль повтор</gold>'
      - '<gradient:#F9A825:#FFEB3B><bold>[!]</bold></gradient> <white>Или просто напишите
        пароль и его повтор в чат</white>'
    # ┌────────────────────────────────
    # │ Отправляет тайтлы (сообщения на весь экран), пока игрок не зарегистрировался.
    # └────────────────────────────────
    title:
    - title: '<gradient:#FFA000:#FFC107><bold>Придумайте пароль</bold></gradient>'
      subtitle: '<white>Введите команду <gold>/reg пароль повтор</gold>'
      duration-fade-in: '500 мсек'
      duration-stay: '3 сек'
      duration-fade-out: '500 мсек'
    - title: '<gradient:#FFA000:#FFC107><bold>Или просто</bold></gradient>'
      subtitle: '<white>напишите пароль и повтор в чат</white>'
      duration-fade-in: '500 мсек'
      duration-stay: '3 сек'
      duration-fade-out: '500 мсек'

  # ┌────────────────────────────────
  # │ Настройки того, что происходит ПОСЛЕ успешной регистрации.
  # │ Сервер, куда игрока отправит, настраивается в general.yml.
  # └────────────────────────────────
  after:
    # ┌────────────────────────────────
    # │ Определяет, сколько времени плагин подержит игрока, прежде чем телепортировать его.
    # └────────────────────────────────
    delay: '2 сек'
    # ┌────────────────────────────────
    # │ Отправляет сообщение на весь экран об успешной регистрации.
    # └────────────────────────────────
    title:
      enabled: true
      title: '<green>Добро пожаловать!'
      subtitle: '<green>Вы успешно зарегистрировались!'
      duration-fade-in: '500 мсек'
      duration-stay: '3 сек 500 мсек'
      duration-fade-out: '1 сек'
    # ┌────────────────────────────────
    # │ Отправляет сообщение в чат об успешной регистрации.
    # └────────────────────────────────
    message:
      enabled: false
      content: '<green>Вы успешно зарегистрировались!'

  # ┌────────────────────────────────
  # │ Общие сообщения, связанные с регистрацией.
  # └────────────────────────────────
  messages:
    passwords-do-not-match: '<red>Пароли не совпадают.'
    no-need: '<red>Вы уже зарегистрированы.'

# ┌────────────────────────────────
# │ Настройки логина.
# └────────────────────────────────
login:
  # ┌────────────────────────────────
  # │ Команда /login [пароль].
  # └────────────────────────────────
  command:
    aliases:
    - 'login'
    - 'l'
    cooldown: '700 мсек'
    arguments:
      password: 'пароль'

  # ┌────────────────────────────────
  # │ Настройки того, что происходит ДО успешного логина.
  # └────────────────────────────────
  before:
    # ┌────────────────────────────────
    # │ Максимальное время, которое игрок может провести в этом состоянии.
    # │ Если игрок не успеет залогиниться, он будет кикнут.
    # └────────────────────────────────
    timeout:
      maximum-time: '2 мин'
      kick-message: '<red>Вы не успели ввести пароль вовремя.'
      # ┌────────────────────────────────
      # │ Отображает боссбар, пока игрок не залогинился.
      # │ Полоска боссбара постепенно уменьшается в соответствии с таймаутом (см. timeout).
      # │ Плейсхолдер <remaining_time> меняется на оставшиеся секунды.
      # └────────────────────────────────
      bossbar:
        enabled: true
        content: '<gradient:#FF5722:#FF9800><bold>[!]</bold></gradient> <white>Введите
          пароль: </white><gold>/l пароль</gold> <gray>(<remaining_time>s)'
        color: 'YELLOW'
        overlay: 'PROGRESS'
    # ┌────────────────────────────────
    # │ Отправляет сообщения по очереди, с равным интервалом, пока игрок не залогинился.
    # └────────────────────────────────
    message:
      enabled: false
      rate: '4 сек'
      contents:
      - '<gradient:#F9A825:#FFEB3B><bold>[!]</bold></gradient> <white>Введите</white>
        <gold>/l пароль</gold>'
      - '<gradient:#F9A825:#FFEB3B><bold>[!]</bold></gradient> <white>Или просто напишите
        пароль в чат</white>'
    # ┌────────────────────────────────
    # │ Отправляет тайтлы (сообщения на весь экран), пока игрок не залогинился.
    # └────────────────────────────────
    title:
    - title: '<gradient:#FFA000:#FFC107><bold>Введите пароль</bold></gradient>'
      subtitle: '<white>Введите команду <gold>/l пароль</gold>'
      duration-fade-in: '500 мсек'
      duration-stay: '3 сек'
      duration-fade-out: '500 мсек'
    - title: '<gradient:#FFA000:#FFC107><bold>Или просто</bold></gradient>'
      subtitle: '<white>напишите пароль в чат</white>'
      duration-fade-in: '500 мсек'
      duration-stay: '3 сек'
      duration-fade-out: '500 мсек'

  # ┌────────────────────────────────
  # │ Настройки того, что происходит ПОСЛЕ логина.
  # │ Сервер, куда игрока отправит, настраивается в general.yml.
  # └────────────────────────────────
  after-full:
    # ┌────────────────────────────────
    # │ Определяет, сколько времени плагин подержит игрока, прежде чем телепортировать его.
    # └────────────────────────────────
    delay: '2 сек'
    # ┌────────────────────────────────
    # │ Отправляет сообщение на весь экран об успешном логине.
    # └────────────────────────────────
    title:
      enabled: true
      title: '<green>С возвращением!'
      subtitle: '<green>Вы успешно вошли!'
      duration-fade-in: '500 мсек'
      duration-stay: '3 сек 500 мсек'
      duration-fade-out: '1 сек'
    # ┌────────────────────────────────
    # │ Отправляет сообщение в чат об успешном логине.
    # └────────────────────────────────
    message:
      enabled: false
      content: '<green>Вы успешно вошли!'

  # ┌────────────────────────────────
  # │ Настройки того, что происходит ПОСЛЕ логина, но когда остались ещё 2FA.
  # └────────────────────────────────
  after-partial:
    # ┌────────────────────────────────
    # │ Определяет, сколько времени плагин подержит игрока, прежде чем перейти к следующей проверке.
    # └────────────────────────────────
    delay: '1 сек 400 мсек'
    # Сообщение на весь экран.
    title:
      enabled: true
      title: '<green>Правильный пароль!'
      subtitle: '<gray>Проверки сейчас продолжатся...'
      duration-fade-in: '300 мсек'
      duration-stay: '800 мсек'
      duration-fade-out: '300 мсек'
    # Сообщение в чате.
    message:
      enabled: false
      content: '<green>Вы ввели правильный пароль! <gray>Продолжаем...'

  # ┌────────────────────────────────
  # │ Общие сообщения, связанные с логином.
  # └────────────────────────────────
  messages:
    no-need: '<red>Вам не нужно вводить пароль.'

# ┌────────────────────────────────
# │ Экспериментальные настройки - могут быть перенесены/изменены/удалены в будущем.
# └────────────────────────────────
experimental:
  # Поставьте true, чтобы при включенном 2FA пароль не спрашивался.
  # Эффект такой же, как от 2FA в версиях до 3.0.0.
  replace-with-bots: false
