# ┌────────────────────────────────
# │ Настройки самого простого способа аутентификации — по IP пользователя.
# │ Когда игрок входит с того же IP-адреса, что и в прошлый раз, его мгновенно пропускает.
# │ Чтобы избежать возможных рисков безопасности, адрес подтверждается не навсегда, а на определённое время.
# │ 
# │ Хотя такое описание может выглядеть небезопасно, на самом деле 100% таких плагинов так и делают.
# │ В Майнкрафте нет других способов реализовать подобное, так как это не веб-браузер, где есть cookie.
# │ Однако, это безопасный способ — "подмены IP" не существует.
# │ Риск может реализоваться разве что в случае, если игрок использует прокси, отключится от него,
# │ а другой человек подключится к этому же прокси-сервису, ему выпадет тот же адрес и он
# │ войдёт на сервер с его ником — это крайне маловероятный сценарий.
# │
# │ Некоторые игроки хотят отключить сессию (чтобы сожитель не зашёл, например), для этого есть:
# │ 1. Команда /logout                                              — для одноразового отключения
# │ 2. Право (настраивается здесь)                                  — для постоянного отключения
# │ 3. Кнопка в интерфейсе сервиса привязки (настраивается здесь)   — для постоянного отключения
# └────────────────────────────────
enabled: true

# Человеческое название этого способа, чтобы в редких случаях показать игрокам.
display-name: 'сессию'

# Максимальная длительность сессии.
max-time: '12 ч'

# Отключение сессии для владельцев определённого права.
disable-by-permission:
  enabled: false
  permission: 'BaronessAuth.method.session.disable'

# Отключение сессии для входящих с определённого IP адреса.
# Поддерживается множество форматов: wildcard, mask, range, CIDR...
# Стандартные настройки предлагают отключать сессию для входов с localhost.
disable-by-address:
  enabled: false
  addresses:
  - '127.0.0.0/8'
  - '::1'

# Сообщение в чат при успешном входе через этот способ.
message:
  enabled: false
  content: '<green>Ваша сессия сохранена, аутентификация не требуется.'

# Сообщение на весь экран при успешном входе через этот способ.
title:
  enabled: true
  title: '<green>С возвращением!'
  subtitle: '<green>Ваша сессия сохранена!'
  duration-fade-in: '500 мсек'
  duration-stay: '2 сек'
  duration-fade-out: '1 сек'
