# ┌────────────────────────────────
# │ Настройки одного из самых интересных методов аутентификации - бот Telegram.
# │.
# │ Его интерфейс знаком многим игрокам, а функции достаточно широки: 2FA, настройки, уведомления и так далее.
# │
# │ [!] Для настройки вам стоит следовать гайду, это займёт всего пару минут:
# │ https://blackbaroness.github.io/docs/pages/baronessauth/guide/telegram.html
# │
# │ Этот бот умеет форматировать сообщения, например, делая текст **жирным**. Вот инструкция:
# │ https://blackbaroness.github.io/docs/pages/baronessauth/guide/telegram.html#%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5
# │
# │ Этот метод хорошо переносит /auth reload - вы можете даже сменить токен, не перезагружая прокси.
# └────────────────────────────────
enabled: false

# Человеческое название этого способа, чтобы в редких случаях показать игрокам.
display-name: '2FA в Telegram'

# ┌────────────────────────────────
# │ Настройки бота - данные для подключения, сообщения, клавиатура и так далее
# └────────────────────────────────
bot:
  # Токен для доступа к боту, его вам даст https://t.me/BotFather
  token: 'вставьте токен сюда'

  # Команды для ввода кода. Если указать пустую команду, любое сообщение будет считаться попыткой ввести код.
  commands:
  - ''
  - '/привязать'
  - '!привязать'
  - '/привязка'
  - '!привязка'
  - '/link'

  # Принимать корректные коды, даже если команда была указана неправильно? На случай тупняка игроков.
  handle-valid-code-even-when-command-is-invalid: true

  # Обрабатывать ли нажатия кнопок, которые были созданы не этим ботом? (ботом до 3.0.0 или вообще чужим)
  handle-unknown-button-click: true

  # Здесь можно включить требование подписаться на каналы или чаты, прежде чем пользоваться ботом.
  # [ВАЖНО] Вы должны добавить бота в эти каналы и группы в качестве админа (права никакие не нужны).
  require-channel-subscription:
    enabled: false
    ids:
    - -1001603471277
    message: '⛔ Для использования бота вы должны подписаться на <вставьте своё>.'

  # Выбор режима форматирования.
  # Гайд: https://blackbaroness.github.io/docs/pages/baronessauth/guide/telegram.html#%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5
  parse-mode: 'MARKDOWN'

  # ┌────────────────────────────────
  # │ Тут находятся все сообщения бота.
  # └────────────────────────────────
  messages:

    # Когда пользователь вызвал невозможное действие (например, пытается привязать аккаунт, который уже удалён).
    invalid-action: '❓ Это действие больше неактуально.'

    # Когда пользователь исчерпал лимит привязки игроков к аккаунту.
    too-many-links-for-account: '⭕ Вы не можете привязать ещё больше игроков к этому
      аккаунту.'

    # Когда нужно сделать что-то с игроком, а он оффлайн.
    player-is-offline: '⭕ Игрок <name> не в сети.'

    # Когда включено подтверждение привязки.
    link-confirmation-required: '⚠ Почти готово! Теперь вернитесь в игру и прочтите
      сообщение в чате.'

    # Когда пользователь успешно привязал аккаунт.
    successful-link: '✅ Вы успешно привязали аккаунт <name>!'

    # Когда пользователю нужно выбрать аккаунт (если у него их несколько).
    select-account: 'Выберите аккаунт:'

    # Когда пользователю нужно принять или отклонить запрос 2FA.
    2fa-request-start: |-
      ⚠ На ваш аккаунт, <name>, пытаются войти с IP <address> (<city>, <country>).

      Тот, кто пытается войти, правильно ввёл ваш пароль!
      Если это не вы, отклоните и смените пароль немедленно (нажмите "сброс пароля")!

    # Когда пользователь принял запрос 2FA.
    2fa-request-accept: '✅ Вы приняли вход на аккаунт <name> с IP <address> (<city>,
      <country>).'

    # Когда пользователь отклонил запрос 2FA.
    2fa-request-decline: |-
      ⭕ Вы отклонили вход на аккаунт <name> с IP <address> (<city>, <country>).

      Если это были не вы, смените пароль немедленно (нажмите "сброс пароля")!

    # Когда пользователь отклонил запрос 2FA.
    2fa-request-cancel: |-
      ⭕ На ваш аккаунт, <name>, пытались войти с IP <address> (<city>, <country>).

      Процесс был отменён - игрок не вошёл.

      Если это были не вы, смените пароль немедленно (нажмите "сброс пароля")!

    # Уведомление при успешном логине.
    notification-login: |-
      🔔 На ваш аккаунт, <name>, вошли, используя <methods>.
      Вход был с IP <address> (<city>, <country>).

    # Когда пользователь не указал код в сообщении.
    invalid-input: |-
      ❓ Вы хотели привязать аккаунт?
      Зайдите на сервер, введите `/link telegram` и полученный код отправьте сюда.

    # Когда пользователь указан неактивный код.
    unknown-code: |-
      ❓ Неизвестный код.
      Зайдите на сервер и введите `/link telegram`, чтобы получить новый.

  # ┌────────────────────────────────
  # │ находятся все кнопки бота.
  # └────────────────────────────────
  buttons:

    # Здесь можно расположить кнопки:
    #    STATUS
    #    RESET_PASSWORD
    #    SETTINGS
    #    TOGGLE_BLOCK
    #    UNLINK
    #    KICK
    #    HELP
    main-keyboard-layout:
    - - 'STATUS'
    - - 'RESET_PASSWORD'
      - 'SETTINGS'
    - - 'TOGGLE_BLOCK'
      - 'UNLINK'
      - 'KICK'
    - - 'HELP'

    # Здесь можно расположить кнопки:
    #   TOGGLE_2FA
    #   TOGGLE_NOTIFICATIONS
    #   TOGGLE_SESSIONS
    #   CLOSE_SETTINGS
    settings-keyboard-layout:
    - - 'TOGGLE_2FA'
    - - 'TOGGLE_NOTIFICATIONS'
    - - 'TOGGLE_SESSIONS'
    - - 'CLOSE_SETTINGS'

    2fa-request:
      accept: '✅ Разрешить'
      decline: '❌ Отклонить'
    status:
      label: '📑 Статус'
      output: |-
        👤 Ник: <name>
        📶 Онлайн: <online>
        📅 Последний логин: <last_login_date>
        🌐 Последний IP: <last_ip> (<last_ip_city>, <last_ip_country>)
        🔔 Уведомления: <notifications>
        🔐 2FA: <2fa>
        💻 Сессии: <sessions>
        🚫 Статус блокировки: <block>
      online: 'да 🟢'
      offline: 'нет 🔴'
    reset-password:
      label: '🔐 Сброс пароля'
      success: '🔐 Новый пароль для <name>: `<password>`'
    settings:
      label: '⚙ Настройки'
      open: '⚙ Вы открыли меню настроек.'
      close: '⚙ Вы закрыли меню настроек.'
    toggle-block:
      label: '⛔ Блокировка'
      success: |-
        ️️️⛔️ Вы переключили блокировку <name>, теперь она <status>.

        Заблокированный аккаунт не сможет входить на сервер, пока вы его не разблокируете.
      status-enabled: 'включена (вход запрещён)'
      status-disabled: 'выключена (вход разрешён)'
    unlink:
      label: '⭕ Отвязка'
      confirmation-description: '⚠ Это действие необратимо!'
      confirmation-yes: '⭕ Я хочу отвязать <name>.'
      confirmation-no: '🟢 Нет, не хочу.'
      success: '⭕ Вы отвязали <name> от этого аккаунта.'
      cancel: 'Вы решили не отвязывать <name> от этого аккаунта.'
    kick:
      label: '💢 Кикнуть'
      success: '💢 Вы кикнули <name>.'
      target-offline: '❌ На сервере сейчас нет <name>.'
      kick-reason: '<red>Владелец аккаунта кикнул вас из бота привязки.'
    help:
      label: '📞 Помощь'
      message: 'Нажмите, чтобы обратиться за помощью:'
      url-button: '📞 Обратиться за помощью'
      url: 'https://blackbaroness.github.io/docs/pages/baronessauth/default_help_link'
    toggle2fa:
      label: '🔗 Переключить 2FA'
      success: '🔗 Вы переключили 2FA для <name>, теперь она <status>.'
      status-enabled: 'включена 🟢'
      status-disabled: 'выключена 🔴'
    toggle-notifications:
      label: '🔔 Переключить уведомления'
      success: '🔔 Вы переключили уведомления для <name>, теперь они <status>.'
      status-enabled: 'включены 🟢'
      status-disabled: 'выключены 🔴'
    toggle-sessions:
      label: '⏱ Переключить сессии'
      success: '⏱ Вы переключили сессии для <name>, теперь они <status>.'
      status-enabled: 'включены 🟢'
      status-disabled: 'выключены 🔴'
    close-settings:
      label: '🚪 Закрыть'

# ┌────────────────────────────────
# │ Настройки привязки со стороны игрока (/link telegram).
# └────────────────────────────────
link:
  # Поставьте false, если хотите оставить метод включённым, но запретить новые привязки.
  accept-new: true

  # Сколько игровых ников можно привязать к одному аккаунту? (максимум 64)
  max-links-per-account: 64

  # Это сообщение видит игрок при начале привязки.
  in-game-start-message: |-
    <gradient:#ffdd00:#fff457><bold>││││ Привязка к Telegram</bold></gradient>
    <color:#ffdd00><bold>│</bold></color> <gray>1.</gray> Вот вам код <click:copy_to_clipboard:'<code>'><hover:show_text:'Нажмите, чтобы скопировать!'><u><code></u></hover></click>
    <color:#ffdd00><bold>│</bold></color> <gray>2.</gray> Перейдите к боту <click:open_url:'https://t.me/bauth_example_bot'><u>@bauth_example_bot</u></click>
    <color:#ffdd00><bold>│</bold></color> <gray>3.</gray> Отправьте ему этот код

  # Это сообщение видит игрок после успешной привязки.
  in-game-success-message: '<green>Вы успешно привязали себя к Telegram <name>!'

  # Когда пользователь исчерпал лимит привязки игроков к аккаунту.
  in-game-too-many-links-for-account: '<red>Вы не можете привязать ещё больше аккаунтов
    к этому Telegram.'

  # Подтверждение при привязке, чтобы избежать угона аккаунтов через демонстрацию первоначального кода.
  confirmation:
    enabled: true
    in-game-message: |-
      <bold><color:#ff0000>[!]</color> <color:#fa414a>↓↓↓ Прочитайте — вас могут скамить! ↓↓↓</color></bold>
      <bold><color:#ff0000>[!]</color> </bold>
      <bold><color:#ff0000>[!]</color> </bold><yellow>Если вы 100% уверены, что хотите привязать свой аккаунт в <u>Telegram <name></u>, введите /link <code>.
      <bold><color:#ff0000>[!]</color> </bold>
      <bold><color:#ff0000>[!]</color> </bold><yellow>Если вы не хотите, просто проигнорируйте это сообщение.
      <bold><color:#ff0000>[!]</color> </bold>
      <bold><color:#ff0000>[!]</color> <color:#fa414a>↑↑↑ Прочитайте — вас могут скамить! ↑↑↑</color></bold>

# ┌────────────────────────────────
# │ Некоторые сообщения, отображаемые в игре.
# └────────────────────────────────
in-game-messages:
  2fa-declined: '<red>Вход был отклонён в Telegram боте.'
  connect-rejected-because-of-block: '<red>Аккаунт был заблокирован через привязанный
    Telegram бот.'
  chat-blocked: '<red>Telegram бот не может отправить вам сообщение. Вы его заблокировали?'

# ┌────────────────────────────────
# │ Настройки логина.
# └────────────────────────────────
login:

  # ┌────────────────────────────────
  # │ Настройки того, что происходит ДО успешного логина.
  # └────────────────────────────────
  before:

    # ┌────────────────────────────────
    # │ Максимальное время, которое игрок может провести в этом состоянии.
    # │ Если игрок не успеет залогиниться, он будет кикнут.
    # └────────────────────────────────
    timeout:
      maximum-time: '2 мин'
      kick-message: '<red>Вы не успели подтвердить вход в боте Telegram вовремя.'
      # Отображает боссбар, пока игрок не залогинился.
      # Полоска боссбара постепенно уменьшается в соответствии с таймаутом (см. timeout).
      # Плейсхолдер <remaining_time> меняется на оставшиеся секунды.
      bossbar:
        enabled: true
        content: '<gradient:#FF5722:#FF9800><bold>[!]</bold></gradient> <white>Подтвердите
          вход </white><gold>в боте Telegram</gold> <gray>(<remaining_time>s)'
        color: 'YELLOW'
        overlay: 'PROGRESS'
    # Отправляет сообщения по очереди, с равным интервалом, пока игрок не залогинился.
    message:
      enabled: false
      rate: '4 сек'
      contents:
      - '<gradient:#F9A825:#FFEB3B><bold>[!]</bold></gradient> <white>Подтвердите
        вход</white> <gold>в боте Telegram</gold>'
    # Отправляет тайтлы (сообщения на весь экран), пока игрок не залогинился.
    title:
    - title: '<gradient:#FFA000:#FFC107><bold>Подтвердите вход</bold></gradient>'
      subtitle: '<white>в боте <gold>Telegram</gold>'
      duration-fade-in: '500 мсек'
      duration-stay: '1 ч'
      duration-fade-out: '500 мсек'

  # ┌────────────────────────────────
  # │ Настройки того, что происходит ПОСЛЕ логина.
  # │ Сервер, куда игрока отправит, настраивается в general.yml.
  # └────────────────────────────────
  after-full:

    # Определяет, сколько времени плагин подержит игрока, прежде чем телепортировать его.
    delay: '2 сек'

    # Отправляет сообщение на весь экран об успешном логине.
    title:
      enabled: true
      title: '<green>С возвращением!'
      subtitle: '<green>Вы успешно вошли!'
      duration-fade-in: '500 мсек'
      duration-stay: '3 сек 500 мсек'
      duration-fade-out: '1 сек'

    # Отправляет сообщение в чат об успешном логине.
    message:
      enabled: false
      content: '<green>Вы успешно вошли!'

  # ┌────────────────────────────────
  # │ Настройки того, что происходит ПОСЛЕ логина, но когда остались ещё 2FA.
  # └────────────────────────────────
  after-partial:

    # Определяет, сколько времени плагин подержит игрока, прежде чем перейти к следующей проверке.
    delay: '1 сек 400 мсек'

    # Сообщение на весь экран.
    title:
      enabled: true
      title: '<green>Вход подтверждён!'
      subtitle: '<gray>Проверки сейчас продолжатся...'
      duration-fade-in: '300 мсек'
      duration-stay: '800 мсек'
      duration-fade-out: '300 мсек'

    # Сообщение в чате.
    message:
      enabled: false
      content: '<green>Вход подтверждён! <gray>Продолжаем...'
