site_name: xenondevs docs
site_url: https://xenondevs.xyz/docs/
repo_url: https://github.com/xenondevs/Docs
repo_name: xenondevs/Docs
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2022 xenondevs
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xenondevs
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/hnEknVWvUe
theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: slate
  features:
    - content.tabs.link
    - navigation.tabs
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - tables
plugins:
  - i18n:
      default_language: en
      languages:
        en: English
        de: Deutsch
nav:
  - "Nova":
      - "Home": "nova/index.md"
      - "For Server Admins":
          - "Setup": "nova/admin/setup.md"
          - "Compatibility": "nova/admin/compatibility.md"
          - "Configuration": "nova/admin/configuration.md"
          - "Recipes": "nova/admin/recipes.md"
      - "API":
          - "Getting Started": "nova/api/index.md"
          - "Protection": "nova/api/protection/protectionintegration.md"
          - "NovaMaterial": "nova/api/material/index.md"
          - "TileEntity":
              - "TileEntity": "nova/api/tileentity/tileentity.md"
              - "TileEntityManager": "nova/api/tileentity/tileentitymanager.md"
          - "Events":
              - "NovaLoadDataEvent": "nova/api/events/novaloaddataevent.md"
              - "TileEntityBreakBlockEvent": "nova/api/events/tileentitybreakblockevent.md"
  - "InvUI":
      - "Home": "invui/index.md"
      - "InvUI Basics": "invui/basics.md"
      - "GUIs":
          - "Normal GUI": "invui/guis/normal.md"
          - "Paged GUI": "invui/guis/paged.md"
      - "Items": "invui/items.md"
      - "Structure": "invui/structure.md"
