# ┌────────────────────────────────
# │ Этот способ аутентификации позволяет вам написать свой быстрый вход через Java API.
# │ 
# │ Если у вас нет плагинов, которые обеспечивают подобную функцию, вам не следует это включать.
# | Подробнее: https://blackbaroness.github.io/docs/pages/baronessauth/guide/api/bypass.html
# └────────────────────────────────
enabled: false

delay:
  # 'true' = пускать игрока в auth сервер, пока ждём завершения AuthPlayerBypassAttemptEvent.
  # 'false' = держать игрока в подвешенном состоянии, пока ждём завершения AuthPlayerBypassAttemptEvent.
  # 'default' = вести себя, как остальные мгновенные способы.
  mode: 'default'
  # Минимальное суммарное время нахождения игрока в auth, включая время выполнения обработчика.
  # Если обработчик выполняется дольше, дополнительной задержки не будет.
  minimum: '2 сек'

# Человеческое название этого способа, чтобы в редких случаях показать игрокам.
display-name: 'bypass'

# Сообщение в чат при успешном входе через этот способ.
message:
  enabled: false
  content: '<green>Вы вошли через bypass.'

# Сообщение на весь экран при успешном входе через этот способ.
title:
  enabled: true
  title: '<green>Вы вошли через bypass.'
  subtitle: '<green>Вы вошли через bypass.'
  duration-fade-in: '500 мсек'
  duration-stay: '2 сек'
  duration-fade-out: '1 сек'

