# ┌────────────────────────────────
# │ Команда /changepassword [старый пароль] [новый пароль].
# │ Она позволяет игроку сменить собственный пароль.
# └────────────────────────────────
aliases:
- 'changepassword'
cooldown: '3 сек'
permissions: []
arguments:
  old-password: 'старый пароль'
  new-password: 'новый пароль'
messages:
  success: '<green>Ваш пароль был изменен.'
