# ┌────────────────────────────────
# │ Команда /logout.
# │ Она позволяет сбросить свою сессию,
# │ то есть отключить автоматический вход при следующем подключении.
# │ 
# │ У этого действия есть побочный эффект - последняя дата входа игрока в /auth stats nick исчезает.
# └────────────────────────────────
aliases:
- 'logout'
cooldown: '10 сек'
permissions: []
messages:
  success: '<green>Ваша сессия сброшена.'
