# ┌────────────────────────────────
# │ Команда /unregister [текущий пароль].
# │ Она позволяет игроку удалить свой аккаунт.
# │ Это удаляет все данные BaronessAuth о нём (пароль, привязки и так далее), но его игровой прогресс останется.
# └────────────────────────────────
aliases:
- 'unregister'
cooldown: '5 сек'
permissions:
- 'BaronessAuth.command.unregister'
arguments:
  password: 'ваш пароль'
messages:
  success: '<green>Ваша регистрация удалена.'
