# ┌────────────────────────────────
# │ Продвинутые настройки BaronessAuth.
# │ 
# │ Сюда попадают только небольшие настройки, которые некуда направить.
# │ Большая часть настроек находится в других файлах.
# │ 
# │ В отличие от general.yml, в этом файле перечислены настройки, которые редко меняют.
# └────────────────────────────────


# ┌────────────────────────────────
# │ Стандартные личные настройки игроков.
# └────────────────────────────────
default-player-parameters:
  # Включена ли у игроков 2FA (двухфакторка) по умолчанию?
  # После привязки у игрока сразу же начнёт работать 2FA, без доп. настроек.
  # Как правило, это должно быть true.
  2fa: true

  # Включены ли у игроков уведомления (от привязки) по умолчанию?
  notifications: true

# ┌────────────────────────────────
# │ Продвинутые настройки базы данных. Не трогайте без причины!
# └────────────────────────────────
database:
  connection-args: []
  cache:
    enabled: true
    size: 10000
    expire-after: '30 мин'

# Устанавливать ли игрокам UUID из БД. Не трогайте без причины!
force-set-player-uuid: false

# Переключает лог "Status checking for server... failed".
log-server-ping-failures: true

# Как часто проверять сервера для балансировки?
update-servers-every: '10 сек'

# Отправлять ли игрока на мертвый сервер (не удаётся подтвердить его доступность),
# если другие варианты закончились?
send-to-dead-servers-if-no-choice: true

# Игрок будет кикнут с указанной причиной, если не удастся найти auth или lobby для него.
no-applicable-server-found-kick-reason: |-
  <red>Не получилось подобрать для вас сервер.
  Если проблема не решится в ближайшее время, обратитесь к администрации.

# Игрок будет кикнут с указанной причиной, если в плагине произойдёт ошибка при каком-либо действии.
generic-error-kick-reason: |-
  <red>Произошла ошибка системы аутентификации.
  Пожалуйста, повторите попытку входа через минуту.
  Если проблема сохраняется, обратитесь к администрации.

# Если BaronessAuth не удаётся подключить игрока к какому-то серверу, плагин кикает игрока с этой причиной.
# Также, в консоли появится лог с причиной, именами игрока и сервера.
server-connect-error-kick-reason: |-
  <red>Не удалось подключить вас к серверу <server>.
  Попробуйте подключиться через минуту.
  Если проблема сохраняется, обратитесь к администрации.

unknown-temporary-command: '<red>Это кликабельное сообщение устарело.'

unsupported-socket-address-type: '<red>Система аутентификации поддерживает подключение
  только с IPv4.'

# Позволяет изменить формат дат, отображаемых в разных местах.
# Как правило, это не стоит менять - тут нужно понимать специфику этих значений.
date-format:
  pattern: 'dd-MM-yyyy HH:mm'
  locale: 'ru-RU'
  zone: 'Europe/Moscow'

geo-lite:
  unknown-country: 'неизвестная страна'
  unknown-city: 'неизвестный город'
  locales:
  - 'ru'
  - 'en'
  cache:
    maximum-size: 5000
    expire-after-access: '10 мин'

# Включает подробные логи (нужно только разработчикам).
debug: false

# Включает ОЧЕНЬ подробные логи (нужно только разработчикам).
trace: false
