# ┌────────────────────────────────
# │ Настройки, касающиеся фильтров подключений игрока.
# │ Как правило, стандартные настройки всем подходят.
# └────────────────────────────────

# -----------------------------------------------------

# ┌────────────────────────────────
# │ Временно запрещает игроку войти на сервер после его выхода.
# │ Многие системы могут работать неправильно, если игрок перезайдёт на сервер слишком быстро.
# └────────────────────────────────
rejoin-delay:
  enabled: true
  cooldown: '500 мсек'
  message: '<red>Вы слишком быстро повторно входите на сервер!'

# ┌────────────────────────────────
# │ Проверяет ники игроков, используя регулярное выражение.
# │ Стандартные настройки повторяют Mojang - 3-16 символов, латиница, цифры и нижнее подчёркивание.
# └────────────────────────────────
player-name-regex:
  enabled: true
  regex: '^[a-zA-Z0-9_]{3,16}$'
  message: |-
    <#b5270b><bold>Ник должен содержать от 3 до 16 символов!</bold>
    <gray>Разрешены:
        <u>латинские буквы</u>,
        <u>цифры</u>,
        <u>символ подчеркивания _</u>

    <white>Вы сейчас входите с ником <u><current_name></u>.

# ┌────────────────────────────────
# │ Требует, чтобы игрок входил с ником в том регистре, в каком он был при регистрации.
# │ Например, игрок, зарегистрированный как BlackBaroness, не сможет войти как blackbaroness.
# │ В Minecraft такие ники считаются одинаковыми, но некоторые плагины могут "не узнать" игрока.
# └────────────────────────────────
player-name-original-case:
  enabled: true
  message: |-
    <red>Вы должны входить с ником <u><correct_name></u>.

    Вы сейчас входите с ником <u><current_name></u>.
