# ┌────────────────────────────────
# │ Настройки, касающиеся защиты от мультиаккаунтов (твинков).
# │
# │ Учитывая ограничения Майнкрафта (смотрите methods/session.yml), мы видим у игрока только ник и IP-адрес.
# │ Соответственно, мы можем понять, мультиаккаунт ли игрок, только по его IP.
# │
# │ Когда игрок подключается впервые, плагин смотрит, какие входы были с этого же адреса за последнее время.
# │ Таким образом мы видим, какие аккаунты наверняка принадлежат этому же человеку.
# │
# │ У этого метода есть все те же неточности, что и у methods/session.yml, но, так как мы смотрим именно
# │ недавние входы, а не все, они незначительны.
# │
# │ Помните, что у каждого бота привязки есть отдельные настройки на похожее ограничение (не по адресу, а по соцсети).
# └────────────────────────────────

# Включена ли защита от мультиаккаунтов?
enabled: true

# После скольки уже зарегистрированных аккаунтов будет отказывать регистрировать новые?
limit: 3

# То самое "за последнее время".
max-login-age: '28 дн'

# С этой причиной кикнет игрока при попытке регистрации, если аккаунтов уже максимум.
kick-reason: |-
  <red>Вы превысили свой лимит мультиаккаунтов!
  Ваши аккаунты: <names> (<accounts>)

# Отключение проверки для входящих с определённого IP адреса.
# Поддерживается множество форматов: wildcard, mask, range, CIDR...
address-whitelist: []

# Оповещения для админов.
notify:
  # Оповещение, когда регистрация мультиаккаунта была отклонена.
  on-disconnect:
    enabled: false
    permission: 'BaronessAuth.notify.multiaccounts.disconnect'
    message: '<yellow>⚠ Отклонён мультаккаунт: <name>! Остальные аккаунты: <accounts>.'

  # Оповещение, когда мультиаккаунт был зарегистрирован.
  on-register:
    enabled: false
    permission: 'BaronessAuth.notify.multiaccounts.register'
    message: '<yellow>⚠ Новый мультиаккаунт: <name>! Остальные аккаунты: <accounts>.'
